<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Assets\CG\**" />
    <Compile Remove="Assets\SE\**" />
    <EmbeddedResource Remove="Assets\CG\**" />
    <EmbeddedResource Remove="Assets\SE\**" />
    <None Remove="Assets\CG\**" />
    <None Remove="Assets\SE\**" />
    <Page Remove="Assets\CG\**" />
    <Page Remove="Assets\SE\**" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Assets\Audio\BGM\school.mp3" />
    <None Remove="Assets\Audio\SE\click.wav" />
    <None Remove="Assets\Backgrounds\bg_school_gate_dusk.jpg" />
    
    <None Remove="Data\story.json" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Assets\Audio\BGM\road.mp3">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\Audio\SE\click.wav">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Data\story.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="ViewModels\" />
    <Folder Include="Resources\" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Assets\Audio\BGM\school.mp3">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Resource Include="Assets\Backgrounds\bg_school_gate_dusk.jpg">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Backgrounds\bg_school_road01_dusk.jpg">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Characters\Misaki\misaki_happy.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Characters\Misaki\misaki_normal.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Characters\Misaki\misaki_sad.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Characters\Misaki\misaki_serious.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Characters\Rina\rina_happy.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Characters\Rina\rina_normal.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

</Project>
